---
- name: bootstrapping and new user
  hosts: raiders
  gather_facts: no

  vars_files:
    - vars/newusers1.yml

  tasks:
  # update the apt catalog
  - name: "update apt with latest repo info"
    raw: "apt update -y"
    become: yes

  # install Python3 and pip3 with ansible
  - name: "Bootstrap python install"
    raw: "apt install -y python3-pip"
    become: yes

  # create a new group
  - name: Create the new group sandbox
    group:
      name: sandbox
      state: present
    become: yes

  - name: Add new users to group 'sandbox'
    user:
      name: "{{ item }}"
      comment: throwaway user account for testing
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      group: sandbox
    become: yes
    loop: "{{ users1 }}"
