---
- name: Playbook with precheck role
  hosts: arista_switches
  connection: network_cli
  become: yes
  become_method: enable
  gather_facts: yes

  tasks:
  - name: Import the precheck data
    import_role:
      name: precheck
